export {Slide1} from './Slide1' 
export { Mensagem } from './Mensagem'
export { Home } from './home'
export { Login } from './Login'
export { Register } from './Register'
export { Perfil } from './Perfil'
export { CadMessage } from './CadMensagem'